In [1]:
# given a dataset that shows which users have purchased an iphone, 
# predict if the customer will
# purchase an iphone or not given their gender, age and salary

In [2]:
import pandas as pd
import numpy as np
import requests
import io


In [3]:
url = 'https://raw.githubusercontent.com/omairaasim/machine_learning/master/project_11_k_nearest_neighbor/iphone_purchase_records.csv'
download = requests.get(url).content
df = pd.read_csv(io.StringIO(download.decode('utf-8')))
df.head()

Gender  Age  Salary  Purchase Iphone
0    Male   19   19000                0
1    Male   35   20000                0
2  Female   26   43000                0
3  Female   27   57000                0
4    Male   19   76000                0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Gender           400 non-null    object
 1   Age              400 non-null    int64 
 2   Salary           400 non-null    int64 
 3   Purchase Iphone  400 non-null    int64 
dtypes: int64(3), object(1)
memory usage: 12.6+ KB


In [5]:
# convert gender to numerical values using label encoder
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender']= le.fit_transform(df['Gender'])
df




Gender  Age  Salary  Purchase Iphone
0         1   19   19000                0
1         1   35   20000                0
2         0   26   43000                0
3         0   27   57000                0
4         1   19   76000                0
..      ...  ...     ...              ...
395       0   46   41000                1
396       1   51   23000                1
397       0   50   20000                1
398       1   36   33000                0
399       0   49   36000                1

[400 rows x 4 columns]

In [6]:
# Let x. be gender, age and salary
# let y be purchase iphone

x = df.iloc[:, 0:3].values
y = df.iloc[:, -1].values



In [7]:
# split data into training and testing set
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state = 0)

print(x_train)

[[     0     44  39000]
 [     1     32 120000]
 [     0     38  50000]
 [     0     32 135000]
 [     0     52  21000]
 [     0     53 104000]
 [     1     39  42000]
 [     1     38  61000]
 [     0     36  50000]
 [     0     36  63000]
 [     0     35  25000]
 [     1     35  50000]
 [     1     42  73000]
 [     0     47  49000]
 [     0     59  29000]
 [     1     49  65000]
 [     0     45 131000]
 [     0     31  89000]
 [     0     46  82000]
 [     0     47  51000]
 [     1     26  15000]
 [     1     60 102000]
 [     0     38 112000]
 [     1     40 107000]
 [     0     42  53000]
 [     1     35  59000]
 [     1     48  41000]
 [     0     48 134000]
 [     0     38 113000]
 [     1     29 148000]
 [     0     26  15000]
 [     1     60  42000]
 [     1     24  19000]
 [     1     42 149000]
 [     0     46  96000]
 [     1     28  59000]
 [     1     39  96000]
 [     1     28  89000]
 [     1     41  72000]
 [     1     45  26000]
 [     0     33  69000]
 [     0     20 

In [8]:
# feature scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train =sc.fit_transform(x_train)
x_test = sc.transform(x_test)




In [9]:
# fit KNN Classifier
from sklearn.neighbors import KNeighborsClassifier
# metric = minkowski and p=2 is Euclidean Distance
# metric = minkowski and p=1 is Manhattan Distance
classifier = KNeighborsClassifier(n_neighbors = 5, metric="minkowski", p=2)
classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [10]:
y_pred = classifier.predict(x_test)

In [11]:
# confusion metrics
from sklearn import metrics
cm = metrics.confusion_matrix(y_test, y_pred)
print (cm)

[[64  4]
 [ 3 29]]


In [12]:
accuracy = metrics.accuracy_score(y_test, y_pred)
print("Accuracy score:",accuracy)

Accuracy score: 0.93


In [13]:
precision = metrics.precision_score(y_test, y_pred) 
print("Precision score:",precision)

Precision score: 0.8787878787878788


In [14]:
recall = metrics.recall_score(y_test, y_pred) 
print("Recall score:",recall)

Recall score: 0.90625
